build:
  image: golang:1.5
  environment:
    - CGO_ENABLED=0
  commands:
    - make deps
    - make vet
    - make build
    - make test

publish:
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: rics3n/drone-azure-storage
    tag: latest
    when:
      branch: master
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: rics3n/drone-azure-storage
    tag: develop
    when:
      branch: develop

#plugin:
#  name: Azure Storage
#  desc: Publish files and artifacts to Azure Storage
#  type: publish
#  image: plugins/drone-azure-storage
#  labels:
#    - azure
#    - storage
